[versions]
# Android Gradle
agp = "8.13.1"
cacheFix = "3.0.3"

# Kotlin
kotlin = "2.2.21"
coroutines = "1.10.2"
dokka = "2.1.0"
binaryValidator = "0.18.1"

# AndroidX
core = "1.17.0"
annotation = "1.9.1"
activity = "1.12.0"
lifecycle = "2.10.0"
dataStore = "1.1.7"
preference = "1.2.1"
testRunner = "1.7.0"

# Compose
compose = "1.9.5"
composeMaterial = "1.7.8"
composeMaterial3 = "1.4.0"

# Google
inAppUpdate = "2.1.0"
inAppReview = "2.0.2"
billing = "8.1.0"

# Images
coil = "3.3.0"

# Developer Tools
spotless = "8.1.0"
doctor = "0.12.1"
jdkDesugar = "2.1.5"
caupain = "1.6.1"


[plugins]
android = { id = "com.android.library", version.ref = "agp" }
android-cacheFix = { id = "org.gradle.android.cache-fix", version.ref = "cacheFix" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-binaryValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryValidator" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
caupain = { id = "com.deezer.caupain", version.ref = "caupain" }

[libraries]
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "jdkDesugar" }

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycle" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-testRunner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }

compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeMaterial" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterial" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-runtime-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "compose" }
compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose-core", version.ref = "coil" }

google-billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing" }
google-inAppUpdate = { group = "com.google.android.play", name = "app-update", version.ref = "inAppUpdate" }
google-inAppReview = { group = "com.google.android.play", name = "review", version.ref = "inAppReview" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
